[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = { version = "1.6.0", features = ["derive"]}
chrono = "0.4.42"
dotenv = "0.15.0"
serde = { version = "1.0.228", features =["derive"]}
serde_json = "1.0.148"
